"$schema" = 'https://starship.rs/config-schema.json'

format = "[Î»](bold blue) $all"

right_format = "$cmd_time"

[aws]
disabled = true

[character]
success_symbol = '[~>](bold green)'

[line_break]
disabled = true
